// Parlor scene — the candlelit observatory hub.
//
// All visuals come from hand-tuned painted assets in /public (generated by
// `imagine`). Procedural textures from textures.ts are still loaded as a
// fallback for any asset that fails to load.

import Phaser from "phaser";
import type { GhostCard } from "../ghosts/types";
import type { GameState } from "../game/state";
import { ghostStatusOf } from "../game/state";
import { buildParlorTextures, T } from "./textures";

export interface ParlorEvents {
  onSummon: (ghost: GhostCard) => void;
  onAltarTry: () => void;
  onInteractMiss?: () => void;
}

interface SceneInit {
  ghosts: GhostCard[];
  finale: GhostCard;
  state: GameState;
  events: ParlorEvents;
}

const PLAYER_SPEED = 180;
const ROOM_W = 28; // tiles  — wider room, more breathing space between mirrors
const ROOM_H = 20;

// Asset keys
const A = {
  floor: "art.floor",
  wall: "art.wall",
  candelabra: "art.candelabra",
  altar: "art.altar",
  player: "art.player",
  mirrorDim: "art.mirror.dim",
  mirror: (id: string) => `art.mirror.${id}`,
};

interface MirrorEntry {
  ghost: GhostCard;
  sprite: Phaser.GameObjects.Image;
  glow: Phaser.GameObjects.Graphics | null;
  placard: Phaser.GameObjects.Text;
}

export class ParlorScene extends Phaser.Scene {
  private ghosts!: GhostCard[];
  private state!: GameState;
  private events_!: ParlorEvents;
  /** Player sprite (the medium). Public so the GameShell debug API can teleport. */
  player!: Phaser.Physics.Arcade.Sprite;
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys;
  private wasd!: { W: Phaser.Input.Keyboard.Key; A: Phaser.Input.Keyboard.Key; S: Phaser.Input.Keyboard.Key; D: Phaser.Input.Keyboard.Key };
  private interactKey!: Phaser.Input.Keyboard.Key;
  private mirrors: MirrorEntry[] = [];
  private altarSprite!: Phaser.GameObjects.Image;
  private altarPlacard!: Phaser.GameObjects.Text;
  private altarGlow!: Phaser.GameObjects.Graphics;
  private nearLabel!: Phaser.GameObjects.Text;
  private inputEnabled = true;
  private hudText!: Phaser.GameObjects.Text;
  private candelabras: Phaser.GameObjects.Image[] = [];

  constructor() { super({ key: "ParlorScene" }); }

  init(data: SceneInit): void {
    this.ghosts = data.ghosts;
    this.state = data.state;
    this.events_ = data.events;
  }

  preload(): void {
    // Procedural fallback textures (for placards, candle dot, etc.)
    buildParlorTextures(this);

    // Painted assets from /public
    this.load.image(A.floor, "/sprites/floor_tile.jpg");
    this.load.image(A.wall, "/sprites/wall_tile.jpg");
    this.load.image(A.candelabra, "/sprites/candelabra.png");
    this.load.image(A.altar, "/sprites/altar.png");
    this.load.image(A.player, "/sprites/medium.png");
    this.load.image(A.mirrorDim, "/mirrors/mirror_dim.png");
    for (const g of this.ghosts) {
      this.load.image(A.mirror(g.id), `/mirrors/${g.id}.png`);
    }
  }

  create(): void {
    this.cameras.main.setBackgroundColor(0x05030a);

    const worldW = ROOM_W * T;
    const worldH = ROOM_H * T;

    // ── Floor: one big painted image stretched across the full world. The
    //    compass roses in the corners become decorative anchors of the parlor.
    const floor = this.add.image(worldW / 2, worldH / 2, A.floor);
    floor.setDisplaySize(worldW, worldH);
    floor.setDepth(0);

    // ── Walls: tile the wall texture around the perimeter (top/bottom/sides).
    //    The painted wall image already has gold trim along its top edge.
    const wallTileSize = 64;
    const wallGroup = this.physics.add.staticGroup();
    // Top wall (with gold trim, taller)
    const topWall = this.add.tileSprite(worldW / 2, wallTileSize / 2, worldW, wallTileSize, A.wall);
    topWall.setTileScale(wallTileSize / 1024); // scale tiles to 64px
    topWall.setDepth(1);
    wallGroup.add(this.physics.add.staticImage(worldW / 2, wallTileSize / 2, A.wall).setVisible(false).setBodySize(worldW, wallTileSize));
    // Bottom wall
    const botWall = this.add.tileSprite(worldW / 2, worldH - wallTileSize / 2, worldW, wallTileSize, A.wall);
    botWall.setTileScale(wallTileSize / 1024).setDepth(1);
    wallGroup.add(this.physics.add.staticImage(worldW / 2, worldH - wallTileSize / 2, A.wall).setVisible(false).setBodySize(worldW, wallTileSize));
    // Left wall
    const lWall = this.add.tileSprite(wallTileSize / 2, worldH / 2, wallTileSize, worldH, A.wall);
    lWall.setTileScale(wallTileSize / 1024).setDepth(1);
    wallGroup.add(this.physics.add.staticImage(wallTileSize / 2, worldH / 2, A.wall).setVisible(false).setBodySize(wallTileSize, worldH));
    // Right wall
    const rWall = this.add.tileSprite(worldW - wallTileSize / 2, worldH / 2, wallTileSize, worldH, A.wall);
    rWall.setTileScale(wallTileSize / 1024).setDepth(1);
    wallGroup.add(this.physics.add.staticImage(worldW - wallTileSize / 2, worldH / 2, A.wall).setVisible(false).setBodySize(wallTileSize, worldH));

    // ── Mirrors along the walls (per ghost) — these are the showpiece.
    // Source mirror sprites are ~848×1264 with significant frame around the
    // portrait. We display generously so the ghost's face is the focal point.
    const MIRROR_W = 156, MIRROR_H = 234;
    for (const g of this.ghosts) {
      // mirror_position is the tile coord of the mirror's CENTER.
      const px = g.mirror_position.x * T;
      const py = g.mirror_position.y * T;
      const status = ghostStatusOf(this.state, g.id);
      const dim = status !== "active";
      const key = dim ? A.mirrorDim : A.mirror(g.id);
      // Soft mystical glow behind active mirrors
      const glow = this.add.graphics();
      glow.fillStyle(g.appearance.body_color, dim ? 0 : 0.22);
      glow.fillCircle(px, py, MIRROR_W);
      glow.setDepth(2);
      glow.setBlendMode(Phaser.BlendModes.SCREEN);
      const sprite = this.add.image(px, py, key).setOrigin(0.5).setDepth(3);
      sprite.setDisplaySize(MIRROR_W, MIRROR_H);
      if (!dim) {
        // Subtle breathing animation on active mirrors
        this.tweens.add({
          targets: sprite,
          scale: { from: sprite.scale, to: sprite.scale * 1.025 },
          duration: 2200 + Math.random() * 600,
          yoyo: true, repeat: -1, ease: "Sine.InOut",
        });
      }
      const fate = status === "resolved" ? "✿ at peace" : status === "banished" ? "✗ banished" : "";
      const placardLines = [g.name, `${g.born ?? "?"}–${g.died ?? "?"}`];
      if (fate) placardLines.push(fate);
      const placard = this.add
        .text(px, py + MIRROR_H / 2 + 12, placardLines.join("\n"), {
          fontFamily: "ui-serif, Georgia, serif",
          fontSize: "11px",
          color: dim ? "#6e6478" : "#e8d8c4",
          align: "center",
          stroke: "#000000",
          strokeThickness: 3,
        })
        .setOrigin(0.5).setDepth(3);
      this.mirrors.push({ ghost: g, sprite, glow, placard });
    }

    // ── Altar at the southern center (Eleanor's mirror)
    const altarX = (ROOM_W / 2) * T;
    const altarY = (ROOM_H - 3.5) * T;
    this.altarGlow = this.add.graphics();
    this.altarGlow.fillStyle(0x9a6cff, this.state.finaleUnlocked ? 0.28 : 0);
    this.altarGlow.fillCircle(altarX, altarY, 180);
    this.altarGlow.setDepth(2);
    this.altarGlow.setBlendMode(Phaser.BlendModes.SCREEN);
    this.altarSprite = this.add.image(altarX, altarY, A.altar).setOrigin(0.5).setDepth(3);
    this.altarSprite.setDisplaySize(280, 190);
    this.altarPlacard = this.add
      .text(altarX, altarY + 110, this.state.finaleUnlocked ? "ELEANOR'S ALTAR\n[E] to commune" : "ELEANOR'S ALTAR\nlocked", {
        fontFamily: "ui-serif, Georgia, serif",
        fontSize: "12px",
        color: this.state.finaleUnlocked ? "#ffd24c" : "#6e6478",
        align: "center",
        stroke: "#000000",
        strokeThickness: 3,
      })
      .setOrigin(0.5).setDepth(3);

    // ── Candelabras: 4 placed in spots that don't crowd the mirrors or altar.
    //    Each casts a warm glow pool on the floor around it.
    const CANDLE_SIZE = 100;
    const candelabraSpots: [number, number][] = [
      [9, 9],                       // mid-left of room
      [ROOM_W - 9, 9],              // mid-right of room
      [4, ROOM_H - 4],              // bottom-left corner area
      [ROOM_W - 4, ROOM_H - 4],     // bottom-right corner area
    ];
    for (const [cx, cy] of candelabraSpots) {
      const px = cx * T + T / 2;
      const py = cy * T + T / 2;
      // Warm pool of light beneath candelabra
      const pool = this.add.graphics();
      pool.fillStyle(0xffb74c, 0.18);
      pool.fillCircle(px, py + 24, CANDLE_SIZE);
      pool.setDepth(1);
      pool.setBlendMode(Phaser.BlendModes.SCREEN);
      this.tweens.add({
        targets: pool, alpha: { from: 0.85, to: 1 },
        duration: 300 + Math.random() * 600, yoyo: true, repeat: -1, ease: "Sine.InOut",
      });
      const c = this.add.image(px, py, A.candelabra);
      c.setDisplaySize(CANDLE_SIZE, CANDLE_SIZE).setDepth(3);
      this.candelabras.push(c);
      this.tweens.add({
        targets: c, alpha: { from: 0.94, to: 1 },
        duration: 300 + Math.random() * 500, yoyo: true, repeat: -1, ease: "Sine.InOut",
      });
    }

    // ── Player (the medium). Bigger and brighter so she reads clearly. The
    //    amber pendant glow is added separately so it pulses with her.
    this.player = this.physics.add.sprite((ROOM_W / 2) * T, (ROOM_H / 2 + 1) * T, A.player);
    this.player.setCollideWorldBounds(true);
    this.player.setDisplaySize(120, 120);
    // Body must use SOURCE pixels (physics is independent of display scale).
    // A small 32px body around the feet feels right for a top-down room.
    this.player.setBodySize(this.player.width * 0.3, this.player.height * 0.3);
    this.player.body!.setOffset(
      this.player.width * 0.35,
      this.player.height * 0.5,
    );
    this.player.setDepth(10);
    // Two-layer halo: a soft warm pool that's always visible, and an inner
    // brighter ring so the medium reads even on dark floor.
    const playerGlowOuter = this.add.graphics();
    playerGlowOuter.fillStyle(0xffc76e, 0.22);
    playerGlowOuter.fillCircle(0, 0, 70);
    playerGlowOuter.setDepth(9);
    playerGlowOuter.setBlendMode(Phaser.BlendModes.SCREEN);
    const playerGlowInner = this.add.graphics();
    playerGlowInner.fillStyle(0xffe6a3, 0.42);
    playerGlowInner.fillCircle(0, 0, 32);
    playerGlowInner.setDepth(9);
    playerGlowInner.setBlendMode(Phaser.BlendModes.SCREEN);
    this.events.on("update", () => {
      playerGlowOuter.x = this.player.x;
      playerGlowOuter.y = this.player.y + 12;
      playerGlowInner.x = this.player.x;
      playerGlowInner.y = this.player.y + 8;
    });
    // Subtle pulse on the inner glow so the player breathes
    this.tweens.add({
      targets: playerGlowInner,
      alpha: { from: 0.42, to: 0.62 },
      duration: 1400, yoyo: true, repeat: -1, ease: "Sine.InOut",
    });
    this.physics.add.collider(this.player, wallGroup);

    // World + camera
    this.physics.world.setBounds(wallTileSize, wallTileSize, worldW - wallTileSize * 2, worldH - wallTileSize * 2);
    this.cameras.main.setBounds(0, 0, worldW, worldH);
    this.cameras.main.startFollow(this.player, true, 0.2, 0.2);

    // ── Inputs
    // CRITICAL: clear captures so the keys (E/W/A/S/D/space) propagate to
    // focused HTML inputs in the séance dialog. See AGENTS.md.
    this.cursors = this.input.keyboard!.createCursorKeys();
    this.wasd = {
      W: this.input.keyboard!.addKey("W"),
      A: this.input.keyboard!.addKey("A"),
      S: this.input.keyboard!.addKey("S"),
      D: this.input.keyboard!.addKey("D"),
    };
    this.interactKey = this.input.keyboard!.addKey("E");
    this.input.keyboard!.clearCaptures();

    // ── HUD (top banner) — translucent gold ribbon so it reads on top of art.
    const hudBg = this.add.graphics();
    hudBg.fillStyle(0x0a060c, 0.78);
    hudBg.fillRoundedRect(this.scale.width / 2 - 280, 4, 560, 28, 4);
    hudBg.lineStyle(1, 0xffd24c, 0.6);
    hudBg.strokeRoundedRect(this.scale.width / 2 - 280, 4, 560, 28, 4);
    hudBg.setScrollFactor(0).setDepth(999);
    this.hudText = this.add
      .text(this.scale.width / 2, 18, "", {
        fontFamily: "ui-serif, Georgia, serif",
        fontSize: "14px",
        color: "#ffd24c",
        align: "center",
        fontStyle: "italic",
      })
      .setOrigin(0.5, 0.5).setScrollFactor(0).setDepth(1000);

    this.nearLabel = this.add
      .text(0, 0, "[E] Commune", {
        fontFamily: "ui-monospace, monospace",
        fontSize: "13px",
        color: "#ffd24c",
        backgroundColor: "rgba(10,8,12,0.92)",
        padding: { left: 10, right: 10, top: 4, bottom: 4 },
      })
      .setDepth(2000).setScrollFactor(0).setVisible(false);
    this.nearLabel.setStroke("#3a2c10", 2);

    // ── Vignette overlay
    const v = this.add.graphics();
    v.setScrollFactor(0).setDepth(900);
    const sw = this.scale.width, sh = this.scale.height;
    for (let i = 0; i < 12; i++) {
      v.fillStyle(0x000000, 0.05);
      v.fillRect(0, 0, sw, sh);
      v.fillStyle(0xffffff, 0);
      v.fillCircle(sw / 2, sh / 2, sh * 0.6 - i * 6);
    }

    this.refreshHud();
  }

  override update(): void {
    if (!this.inputEnabled) {
      this.player.setVelocity(0, 0);
      this.nearLabel.setVisible(false);
      return;
    }
    const left = this.cursors.left?.isDown || this.wasd.A.isDown;
    const right = this.cursors.right?.isDown || this.wasd.D.isDown;
    const up = this.cursors.up?.isDown || this.wasd.W.isDown;
    const down = this.cursors.down?.isDown || this.wasd.S.isDown;

    let vx = 0, vy = 0;
    if (left) vx -= 1; if (right) vx += 1;
    if (up) vy -= 1; if (down) vy += 1;
    if (vx !== 0 && vy !== 0) { vx *= 0.707; vy *= 0.707; }
    this.player.setVelocity(vx * PLAYER_SPEED, vy * PLAYER_SPEED);

    // Find nearest interactable
    let bestDist = 90 * 90;
    let target: { kind: "mirror"; ghost: GhostCard } | { kind: "altar" } | null = null;
    for (const m of this.mirrors) {
      if (ghostStatusOf(this.state, m.ghost.id) !== "active") continue;
      const dx = m.sprite.x - this.player.x;
      const dy = m.sprite.y + 30 - this.player.y;
      const d = dx * dx + dy * dy;
      if (d < bestDist) { bestDist = d; target = { kind: "mirror", ghost: m.ghost }; }
    }
    {
      const dx = this.altarSprite.x - this.player.x;
      const dy = this.altarSprite.y - this.player.y;
      const d = dx * dx + dy * dy;
      if (d < bestDist) { bestDist = d; target = { kind: "altar" }; }
    }

    if (target) {
      const cam = this.cameras.main;
      let labelText = "", anchorX = 0, anchorY = 0;
      if (target.kind === "mirror") {
        labelText = `[E] Commune with ${target.ghost.name}`;
        const m = this.mirrors.find((m) => m.ghost.id === target.ghost.id)!;
        anchorX = m.sprite.x; anchorY = m.sprite.y - 90;
      } else {
        labelText = this.state.finaleUnlocked
          ? `[E] Approach the altar — Eleanor waits`
          : `[E] (locked — gather more mementos)`;
        anchorX = this.altarSprite.x; anchorY = this.altarSprite.y - 90;
      }
      this.nearLabel.setText(labelText).setVisible(true);
      this.nearLabel.setPosition(
        anchorX - cam.scrollX - this.nearLabel.width / 2,
        anchorY - cam.scrollY,
      );
    } else {
      this.nearLabel.setVisible(false);
    }

    if (Phaser.Input.Keyboard.JustDown(this.interactKey)) {
      if (target?.kind === "mirror") this.events_.onSummon(target.ghost);
      else if (target?.kind === "altar") this.events_.onAltarTry();
      else this.events_.onInteractMiss?.();
    }
  }

  setInputEnabled(enabled: boolean): void {
    this.inputEnabled = enabled;
    if (!enabled) {
      this.player.setVelocity(0, 0);
      this.nearLabel.setVisible(false);
    }
  }

  refreshGhostState(state: GameState): void {
    this.state = state;
    for (const m of this.mirrors) {
      const status = ghostStatusOf(state, m.ghost.id);
      const dim = status !== "active";
      m.sprite.setTexture(dim ? A.mirrorDim : A.mirror(m.ghost.id));
      m.sprite.setDisplaySize(96, 144);
      m.placard.setColor(dim ? "#6e6478" : "#e8d8c4");
      const fate = status === "resolved" ? "✿ at peace" : status === "banished" ? "✗ banished" : "";
      const lines = [m.ghost.name, `${m.ghost.born ?? "?"}–${m.ghost.died ?? "?"}`];
      if (fate) lines.push(fate);
      m.placard.setText(lines.join("\n"));
      if (m.glow) {
        m.glow.clear();
        m.glow.fillStyle(m.ghost.appearance.body_color, dim ? 0 : 0.18);
        m.glow.fillCircle(m.sprite.x, m.sprite.y, 96);
      }
    }
    if (state.finaleUnlocked) {
      this.altarPlacard.setText("ELEANOR'S ALTAR\n[E] to commune");
      this.altarPlacard.setColor("#ffd24c");
      this.altarGlow.clear();
      this.altarGlow.fillStyle(0x9a6cff, 0.28);
      this.altarGlow.fillCircle(this.altarSprite.x, this.altarSprite.y, 140);
    }
    this.refreshHud();
  }

  private refreshHud(): void {
    const total = this.ghosts.length;
    const peace = this.ghosts.filter((g) => ghostStatusOf(this.state, g.id) === "resolved").length;
    const banished = this.ghosts.filter((g) => ghostStatusOf(this.state, g.id) === "banished").length;
    const parts = [`Echoes of the Departed`];
    parts.push(`at peace ${peace}/${total}`);
    if (banished) parts.push(`banished ${banished}`);
    parts.push(`mementos ${this.state.mementos.length}`);
    this.hudText.setText(parts.join("    ·    "));
  }
}
